Added Weight plot
ing-bank/skorecard pull request #65
Opened 2021-09-27 16:50 UTC by satya-pattnaik

With reference to #58 .

2021-09-27 16:56 UTC, satya-pattnaik commented
@orchardbirds How do I add reviewers here?

2021-09-28 12:21 UTC, orchardbirds requested changes
Love the commitment Satya, and this is really clean. 

One main thing that I would love to see added: we generate the stats from our Logistic Regression class in `linear_model/linear_model.py`

I would add/import the function here too, so that I can do the following:

```python
from skorecard.datasets import load_uci_credit_card
    from skorecard.bucketers import EqualFrequencyBucketer
    from skorecard.linear_model import LogisticRegression
    from sklearn.pipeline import Pipeline
    from sklearn.preprocessing import OneHotEncoder

    X, y = load_uci_credit_card(return_X_y=True)

    pipeline = Pipeline([
        ('bucketer', EqualFrequencyBucketer(n_bins=10)),
        ('clf', LogisticRegression(calculate_stats=True))
    ])
    pipeline.fit(X, y)
   pipeline.named_steps['clf'].get_stats()
   pipeline.named_steps['clf'].plot_stats()

```
It doesn't have to be called `plot_stats`, but in this way we don't even need to pass it the `stats` dataframe, it can do it automatically. 

I think to do this you can add the following to `reporting/__init__.py`:
```python
"""Import required create_report."""
from .report import build_bucket_table, psi, iv
from .plotting import (
    plot_bucket_table,
    weight_plot,
)

__all__ = ["build_bucket_table", "plot_bucket_table", "psi", "iv", "weight_plot"]

```


Thanks again for the hard work!

2021-09-28 12:21 UTC, orchardbirds commented on skorecard/reporting/plotting.py
> +    from sklearn.pipeline import Pipeline
Don't forget to import `weight_plot` as well

2021-09-28 12:21 UTC, orchardbirds commented on skorecard/reporting/plotting.py
> +    stats["[0.025"] = stats["Coef."] - 1.96 * stats["Std.Err"]
To be honest, I'm not a fan of these column names. Maybe something like `conf_interval_0.025` etc.

2021-10-19 13:08 UTC, orchardbirds commented
Thanks for the changes! I am actually on paternity leave right now so don't have time to review. I will in November, however. Sorry for the delay, but I wanted to let you know :)

2021-11-16 08:53 UTC, orchardbirds approved these changes
This looks nice, thanks for being patient

2021-11-16 08:55 UTC, merged